version: '3.4'

networks:
  default:
    driver: bridge

services:
  phpmyadmin:
    container_name: ${APPLICATION_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - ${MYSQL_ADMIN_PORT}:80
    links:
      - mysql:db
    depends_on:
      - mysql
    environment:
      PMA_ABSOLUTE_URI: ${MYSQL_ADMIN_DOMAIN}
    networks:
      - default